### ISSUE TITLE
Empty consumers page

### ISSUE THREAD

**Issue by aaronsdevera** [brianwarehime/threatnote#11]
Consumers page not populated with data.
<img width="1145" alt="Screen Shot 2020-05-28 at 8 32 22 PM" src="https://user-images.githubusercontent.com/5042762/83207976-7a3d0200-a122-11ea-951a-292bebc8c3da.png">

**Comment by brianwarehime** [comment]
Hey, did you add any consumers to one of the requirements yet? This page is only populated once you add a consumer

**Comment by aaronsdevera** [comment]
aha! given your response @brianwarehime to https://github.com/brianwarehime/threatnote/issues/13
then i do believe there are no consumers, as they did not fit the allow list.
Closing!
